#!/bin/bash

# Results in catalog-sync-service generating and publishing an updated 
# app config for the given app.
#
# Usage:
#
#   catalog-sync [CIRCLE_CI_INTEGRATIONS_URL] [USER] [PASS] [ENTITY_NAME] [TYPE]
#

set -e

: ${CIRCLE_BRANCH?"Missing required env var"}
BRANCH=$CIRCLE_BRANCH
if [[ $BRANCH != "master" ]]; then
  echo "Skipping sync for non-master branch"
  exit 0
fi

# User supplied args
CIRCLE_CI_INTEGRATIONS_URL=$1
if [[ -z $CIRCLE_CI_INTEGRATIONS_URL ]]; then echo "Missing arg1 CIRCLE_CI_INTEGRATIONS_URL" && exit 1; fi
USER=$2
if [[ -z $USER ]]; then echo "Missing arg2 USER" && exit 1; fi
PASS=$3
if [[ -z $PASS ]]; then echo "Missing arg3 PASS" && exit 1; fi
ENTITY_NAME=$4
if [[ -z $ENTITY_NAME ]]; then echo "Missing arg4 ENTITY_NAME" && exit 1; fi
TYPE=$5
if [[ -z $TYPE ]]; then echo "Missing arg5 TYPE" && exit 1; fi

echo "Posting to catalog sync service..."
SC=$(curl -u $USER:$PASS \
  --retry 5 \
  -w "%{http_code}" \
  -H "Content-Type: application/json" \
  -X POST \
  $CIRCLE_CI_INTEGRATIONS_URL/catalogEntity?entity=$ENTITY_NAME&type=$TYPE)

if [ "$SC" -eq 200 ]; then
  echo "Successfully published app catalog config"
  exit 0
else
  echo "Failed to publish app catalog config"
  exit 1
fi
