#!/bin/bash

# Publishes build and application objects to Catapult.
#
# Usage:
#
#   catapult-publish [CATAPULT_URL] [CATAPULT_USER] [CATAPULT_PASS] [APP_NAME]
#
# Required circleci provided environment variables:
#
#  CIRCLE_PROJECT_REPONAME
#  CIRCLE_PROJECT_USERNAME
#  CIRCLE_BUILD_NUM
#

set -e

# User supplied args
CATAPULT_URL=$1
if [[ -z $CATAPULT_URL ]]; then echo "Missing arg1 CATAPULT_URL" && exit 1; fi
CATAPULT_USER=$2
if [[ -z $CATAPULT_USER ]]; then echo "Missing arg2 CATAPULT_USER" && exit 1; fi
CATAPULT_PASS=$3
if [[ -z $CATAPULT_PASS ]]; then echo "Missing arg3 CATAPULT_PASS" && exit 1; fi
APP_NAME=$4
if [[ -z $APP_NAME ]]; then echo "Missing arg4 APP_NAME" && exit 1; fi

# Set automatically by CircleCI
: ${CIRCLE_PROJECT_REPONAME?"Missing required env var"}
REPO=$CIRCLE_PROJECT_REPONAME
: ${CIRCLE_PROJECT_USERNAME?"Missing required env var"}
USER=$CIRCLE_PROJECT_USERNAME
: ${CIRCLE_BUILD_NUM?"Missing required env var"}
BUILD_NUM=$CIRCLE_BUILD_NUM

RUN_TYPE=$(grep type "launch/${APP_NAME}.yml" | cut -d' ' -f4)
if [[ $RUN_TYPE != "docker" ]]; then
    echo "Can only publish applications with run type 'docker' using this script; got ${RUN_TYPE}"
    exit 1
fi

echo "Publishing to catapult..."
echo "Using data:"
DATA="{\"username\":\"$USER\",\"reponame\":\"$REPO\",\"buildnum\":$BUILD_NUM,\"appname\":\"$APP_NAME\"}"
echo "${DATA}"
echo "================================================================================"
SC=$(curl -u $CATAPULT_USER:$CATAPULT_PASS \
  --retry 5 \
  -w "%{http_code}" \
  --output catapult.out \
  -H "Content-Type: application/json" \
  -X POST \
  -d "${DATA}" \
  $CATAPULT_URL)

if [ "$SC" -eq 200 ]; then
  echo "Successfully published catapult application"
  rm -f catapult.out
else
  echo "Failed to publish catapult application"
  echo "------------------------------------------------"
  cat catapult.out
  echo ""
  echo "------------------------------------------------"
  rm -f catapult.out
  exit 1
fi

# publish catalog app config
CATALOG_SYNC_SCRIPT="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )/catalog-sync"
CIRCLE_CI_INTEGRATIONS_URL=$(dirname $CATAPULT_URL)
"${CATALOG_SYNC_SCRIPT}" $CIRCLE_CI_INTEGRATIONS_URL $CATAPULT_USER $CATAPULT_PASS $APP_NAME
