#!/bin/bash

# Results in catalog-sync-service generating and publishing an updated 
# app config for the given app.
#
# Usage:
#
#   catalog-sync [CIRCLE_CI_INTEGRATIONS_URL] [USER] [PASS] [ENTITY_NAME] [TYPE]
#

set -e

: ${CIRCLE_BRANCH?"Missing required env var"}
BRANCH=$CIRCLE_BRANCH

DRY_RUN="true"
if [[ $BRANCH == "master" ]]; then
  DRY_RUN="false"
fi

# User supplied args
CIRCLE_CI_INTEGRATIONS_URL=$1
if [[ -z $CIRCLE_CI_INTEGRATIONS_URL ]]; then echo "Missing arg1 CIRCLE_CI_INTEGRATIONS_URL" && exit 1; fi
USER=$2
if [[ -z $USER ]]; then echo "Missing arg2 USER" && exit 1; fi
PASS=$3
if [[ -z $PASS ]]; then echo "Missing arg3 PASS" && exit 1; fi
ENTITY_NAME=$4
if [[ -z $ENTITY_NAME ]]; then echo "Missing arg4 ENTITY_NAME" && exit 1; fi
TYPE=$5
if [[ -z $TYPE ]]; then echo "Missing arg5 TYPE" && exit 1; fi


# Extract base URL (protocol + domain) as sometimes users might include a path after the domain
BASE_URL=$(echo "$CIRCLE_CI_INTEGRATIONS_URL" | awk -F'/' '{print $1"//"$3}')

echo "Posting to catalog sync service..."
SC=$(curl -u $USER:$PASS \
  --retry 5 \
  -w "%{http_code}" \
  -H "Content-Type: application/json" \
  -X POST \
  "$BASE_URL/catalogEntity?entity=$ENTITY_NAME&type=$TYPE&branch=$BRANCH&dryRun=$DRY_RUN")

if [ "$SC" -eq 200 ]; then
  echo "Successfully published app catalog config"
  exit 0
else
  echo "Failed to publish app catalog config"
  exit 1
fi
