#!/bin/bash

# Submits an application to Dapple deployment pipeline
#
# Usage:
#
#   dapple-deploy [DAPPLE_URL] [DAPPLE_USER] [DAPPLE_PASS] [APP_NAME] [[DEPLOY_ENV] [DEPLOY_STRATEGY]]
#
# Required circleci provided environment variables:
#
#  CIRCLE_PROJECT_REPONAME
#  CIRCLE_PROJECT_USERNAME
#  CIRCLE_BUILD_NUM
#

set -e

if [ $# -ne 4 ] && [ $# -ne 5 ] && [ $# -ne 6 ]; then
    echo "Incorrect number of arguments given. Expected at least 4, received $#"
    echo "Usage: dapple-deploy [DAPPLE_URL] [DAPPLE_USER] [DAPPLE_PASS] [APP_NAME] [[DEPLOY_ENV] [DEPLOY_STRATEGY]]"
    exit 1
fi

# User supplied args
DAPPLE_URL=$1
DAPPLE_USER=$2
DAPPLE_PASS=$3
APP_NAME=$4
# TODO: as part of INFRANG-4341 we would like to get rid of these 2 values. In the interim they will be ignored if the new launch config format is used.
# deploy env and deploy strategy get default values, if not specified
DEPLOY_ENV=${5:-clever-dev}
DEPLOY_STRATEGY=${6:-confirm-then-deploy}

# Set automatically by CircleCI
: ${CIRCLE_PROJECT_REPONAME?"Missing required env var"}
REPO=$CIRCLE_PROJECT_REPONAME
: ${CIRCLE_PROJECT_USERNAME?"Missing required env var"}
USER=$CIRCLE_PROJECT_USERNAME
: ${CIRCLE_BUILD_NUM?"Missing required env var"}
BUILD_NUM=$CIRCLE_BUILD_NUM
BRANCH=$CIRCLE_BRANCH

# Safety Checks
if [ "$DEPLOY_ENV" = "production" -a "$BRANCH" != "master" ]; then
  echo "ERROR: Cannot publish into production from a non-master branch"
  exit 1
fi

if [ "$DEPLOY_ENV" != "production" -a "$DEPLOY_ENV" != "clever-dev" -a "$DEPLOY_ENV" != "dev-infra" ]; then
  echo "ERROR: Only 'production', 'clever-dev', and 'dev-infra' are supported deployment environments"
  exit 1
fi

echo "Publishing to dapple..."
SC=$(curl -u $DAPPLE_USER:$DAPPLE_PASS \
  -w "%{http_code}" \
  --output dapple.out \
  -H "Content-Type: application/json" \
  -X POST \
  -d "{\"username\":\"$USER\",\"reponame\":\"$REPO\",\"buildnum\":$BUILD_NUM,\"appname\":\"$APP_NAME\",\"environment\":\"$DEPLOY_ENV\",\"strategy\":\"$DEPLOY_STRATEGY\"}" \
  $DAPPLE_URL)

if [ "$SC" -eq 200 ]; then
  echo "Successfully published application to dapple"
  rm -f dapple.out
  exit 0
else
  echo "Failed to publish application to dapple"
  echo "------------------------------------------------"
  cat dapple.out
  echo ""
  echo "------------------------------------------------"
  rm -f dapple.out
  exit 1
fi
