#!/bin/bash

# Logs into ECR, then builds and pushes docker image. Docker 
# image is tagged with 7 character git commit SHA.
#
# Usage:
#
#   docker-publish


set -e

DIR=$(dirname "$0")
. $DIR/utils

# enable experimental cli features for 'docker manifest'
if [ -f "~/.docker/config.json" ]; then
    tmp=$(mktemp)
    jq '. + {"experimental":"enabled"}' ~/.docker/config.json > "$tmp"
    mv $tmp ~/.docker/config.json
else
    mkdir ~/.docker
    echo '{"experimental":"enabled"}' > ~/.docker/config.json
fi

image_exists() {
    docker manifest inspect "$1" > /dev/null
    status=$?
    if $(exit $status); then
        true
    else
        false
    fi
}

check_ecr_vars() {
  # ECR required env vars
  if [[ -z $ECR_ACCOUNT_ID ]]; then echo "Missing var for ECR: ECR_ACCOUNT_ID" && exit 1; fi
  if [[ -z $ECR_PUSH_SECRET ]]; then echo "Missing var for ECR: ECR_PUSH_SECRET" && exit 1; fi
}

ecr_login(){
  REGION=$1
  install_awscli
  eval $(AWS_ACCESS_KEY_ID=$ECR_PUSH_ID AWS_SECRET_ACCESS_KEY=$ECR_PUSH_SECRET aws ecr --region $REGION get-login --include-email) || eval $(AWS_ACCESS_KEY_ID=$ECR_PUSH_ID AWS_SECRET_ACCESS_KEY=$ECR_PUSH_SECRET aws ecr --region $REGION get-login --no-include-email)
}

push_ecr_image(){
  REGION=$1
  ECR_URI=$ECR_ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$REPO:$SHORT_SHA
  if image_exists $ECR_URI > /dev/null; then
      echo "ECR image exists, refusing to overwrite"
      exit 1
  fi
  docker tag $ORG/$REPO:$SHORT_SHA $ECR_URI
  docker push $ECR_URI
}

# Set automatically by CircleCI
: ${CIRCLE_PROJECT_REPONAME?"Missing required env var"}
REPO=$CIRCLE_PROJECT_REPONAME
: ${CIRCLE_SHA1?"Missing required env var"}
SHORT_SHA=${CIRCLE_SHA1:0:7}

ORG=clever

ECR_REGION_PRIMARY=us-west-1
ECR_REGION_SECONDARY=us-west-2

echo "Docker version..."
docker version

# Check CLI + env vars for ECR
check_ecr_vars

# ECR login.
echo "Logging into ECR..."
ecr_login $ECR_REGION_PRIMARY
ecr_login $ECR_REGION_SECONDARY

echo "Building docker image..."
docker build -t $ORG/$REPO:$SHORT_SHA .

echo "Pushing to ECR..."
push_ecr_image $ECR_REGION_PRIMARY
push_ecr_image $ECR_REGION_SECONDARY
