#!/bin/bash

# Moves a golang project from the default location to the golang workspace
#
# Usage:
#
#   golang-move-project
#
# Note: This script relies on CircleCI specific environment variables:
#   - HOME
#   - CIRCLE_PROJECT_REPONAME
#   - CIRCLE_PROJECT_USERNAME


set -e


move_project() { 
    # User supplied args
    SRC=$1
    if [[ -z $SRC ]]; then echo "Missing arg1 SRC" && exit 1; fi

    DEST=$2
    if [[ -z $DEST ]]; then echo "Missing arg2 DEST" && exit 1; fi


    # Delete anything already in the destination
    if [ -e $DEST ]; then
        echo -n "Cleaning up previous contents in the destination..."
        rm -rf $DEST
        echo "Done"
    fi

    # Create the parent destination dir if it does not exist
    PARENT_DIR=`dirname $DEST`
    if [ ! -d $PARENT_DIR ]; then
        echo -n "Creating parent dir..."
        mkdir -p $PARENT_DIR
        echo "Done"
    fi

    # move the src into the destination
    echo -n "Moving files..."
    mv $SRC $DEST
    echo "Done"

    # re-create the src dir for circleci
    mkdir $SRC
}

move_project $HOME/$CIRCLE_PROJECT_REPONAME $HOME/.go_workspace/src/github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
