#!/bin/bash

# Installs a specific version of golang.
# Assumes OS is linux-amd64.
#
# Usage:
#
#   golang-install [GO_VERSION]
#
#   e.g. `golang-install 1.7.4`

set -e

# User supplied args
GO_VERSION=$1
if [[ -z $GO_VERSION ]]; then echo "Missing arg1 GO_VERSION" && exit 1; fi

echo "Attempting to download Go version '$GO_VERSION'..."

GODIST=go$GO_VERSION.linux-amd64.tar.gz

INSTALL_ROOT=/usr/local

# Download the golang package if needed
mkdir -p download
if [ ! -e download/$GODIST ]; then
    echo -n "Downloading $GODIST ..."
    curl -s -o download/$GODIST https://storage.googleapis.com/golang/$GODIST
    echo "Done"
fi

# Cleanup any existing versions and install the new one
sudo rm -rf $INSTALL_ROOT/go
echo -n "Extracting $GODIST"
sudo tar -C $INSTALL_ROOT -xzf download/$GODIST
echo "Done."
echo "Golang installed successfully"
