#!/bin/bash

# Submits an application to integration-testing-service
#
# Usage:
#
#   integration-test [TESTING_SERVICE_URL] [TESTING_SERVICE_USER] [TESTING_SERVICE_PASS] [APP_NAME] [[TESTS_TO_RUN]]
#
# Required circleci provided environment variables:
#
#  CIRCLE_PROJECT_REPONAME
#  CIRCLE_PROJECT_USERNAME
#  CIRCLE_BUILD_NUM
#

set -e

if [ $# -ne 4 ] && [ $# -ne 5 ] && [ $# -ne 6 ]; then
    echo "Incorrect number of arguments given. Expected at least 4, received $#"
    echo "Usage: integration-test [TESTING_SERVICE_URL] [TESTING_SERVICE_USER] [TESTING_SERVICE_PASS] [APP_NAMES] [[TESTS_TO_RUN]]"
    exit 1
fi

# User supplied args
TESTING_SERVICE_URL=$1
TESTING_SERVICE_USER=$2
TESTING_SERVICE_PASS=$3
# APP_NAMES is a comma-separated list of applications e.g. app-service,sso-app-service
APP_NAMES=$4
# TESTS_TO_RUN gets a default value, if not specified
# It is a JSON value whose schema corresponds with our internal testing spec schema.
TESTS_TO_RUN=${5:-'[{"type": "launchpad"}]'}

# Set automatically by CircleCI
: ${CIRCLE_PROJECT_REPONAME?"Missing required env var"}
REPO=$CIRCLE_PROJECT_REPONAME
: ${CIRCLE_PROJECT_USERNAME?"Missing required env var"}
USER=$CIRCLE_PROJECT_USERNAME
: ${CIRCLE_BUILD_NUM?"Missing required env var"}
BUILD_NUM=$CIRCLE_BUILD_NUM

# Convert APP_NAMES (comma-separated list of apps e.g appA,appB) into a JSON array
APPS=$(echo "${APP_NAMES}" |
	   sed 's/,/\n/g' | # a,b,c => a\nb\nc
	   jq --raw-input | # a\nb\nc => "a"\n"b"\n"c"\n ; raw-input means read the input as strings (one per line), not as JSON,
	                    # but we still output as JSON, thus we add the quotes
	   jq --slurp --compact-output # "a"\n"b"\n"c"\n => ["a","b","c"]  ; slurp to combine lines into a JSON array
    )

echo "Submitting to integration-testing-service..."
SC=$(curl -u $TESTING_SERVICE_USER:$TESTING_SERVICE_PASS \
  -w "%{http_code}" \
  --output integration-tests.out \
  -H "Content-Type: application/json" \
  -X POST \
  -d "{\"username\":\"$USER\",\"reponame\":\"$REPO\",\"buildnum\":$BUILD_NUM,\"apps\":${APPS},\"tests\":${TESTS_TO_RUN}}" \
  $TESTING_SERVICE_URL)

if [[ $SC -eq 200 ]]; then
  echo "Successfully submitted to integration-testing-service"
  JOB_ID=$(cat integration-tests.out | jq -r '.jobId')
  rm -f integration-tests.out
else
  echo "Failed to submit tests to integration-testing-service"
  echo "------------------------------------------------"
  cat integration-tests.out
  echo ""
  echo "------------------------------------------------"
  rm -f integration-tests.out
  exit 1
fi

echo "Job ID: $JOB_ID"

echo "Waiting 1 minute before polling"
sleep 1m

echo "Polling for test completion"

# Polling 60 times at 30 seconds each (30 minutes)
# The timeout for the workflow is at 30 minutes, minus reserved time for cleanup.
# Since we aren't planning on canceling the workflow on any shorter timeout, we should poll for that long.
MAX_POLLS=60
for ((i=1;i<=MAX_POLLS;i++))
do
  sleep 30s
  SC=$(curl -u $TESTING_SERVICE_USER:$TESTING_SERVICE_PASS \
    -w "%{http_code}" \
    --output integration-tests.out \
    -H "Content-Type: application/json" \
    -X GET \
    -s -S \
    "$TESTING_SERVICE_URL?JobID=$JOB_ID")
  if [[ $SC -eq 200 ]]; then
    echo "------------------------------------------------"
    STATUS=$(cat integration-tests.out | jq '.status')
    echo "Tests status: $STATUS"
    if [[ $STATUS == '"succeeded"' ]]; then
      rm -f integration-tests.out
      exit 0
    elif [[ $STATUS == '"testsFailed"' ]]; then
      # in this case, .message is a single JSON string encoding a JSON blob of the test output
      echo "------------------------------------------------"
      echo "Test output:"
      cat integration-tests.out | jq -r '.message' | jq
      echo "------------------------------------------------"
      ENV=$(jq .environment < integration-tests.out)
      echo "Tests ran in staging environment: ${ENV:-<not sure>}"
      rm -f integration-tests.out
      exit 1
    elif [[ $STATUS == '"systemError"' ]]; then
      echo "------------------------------------------------"
      cat integration-tests.out
      echo ""
      echo "------------------------------------------------"
      rm -f integration-tests.out
      exit 1
    fi
  else
    echo "------------------------------------------------"
    echo $SC
  fi
done

echo "------------------------------------------------"
echo "Tests still not finished, timing out"
rm -f integration-tests.out
exit 1
