#!/bin/bash

# Installs Mongo of a specific version, rather than the default version in CircleCI.
#
# Usage:
#
#   mongo-install [VERSION]
#
# Examples:
#
#   mongo-install 2.4
#   mongo-install 2.6
#   mongo-install 2.6.12

set -e

# Get user args
VERSION=$1
if [[ -z $VERSION ]]; then echo "Missing arg1 VERSION" && exit 1; fi

if [ "$VERSION" == "2.4" ]; then VERSION="2.4.12"; fi
if [ "$VERSION" == "2.6" ]; then VERSION="2.6.12"; fi

echo "Setting up Mongo version $VERSION..."

echo "Stopping and removing currently installed Mongo..."
sudo service mongod stop || echo "mongod was not running"
sudo apt-get purge mongodb-org*

echo "Downloading and installing Mongo ..."
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/mongodb.list
sudo apt-get update

if [ "${VERSION:0:3}" == "2.4" ]; then
    sudo apt-get install -y mongodb-10gen=$VERSION
else
    sudo apt-get install \
        mongodb-org=$VERSION \
        mongodb-org-server=$VERSION \
        mongodb-org-shell=$VERSION \
        mongodb-org-mongos=$VERSION \
        mongodb-org-tools=$VERSION
fi

echo "Checking installed Mongo version..."
mongo --version

echo "Mongo installed successfully"
