#!/bin/bash

# Installs a specific Mongo version, rather than the default version in CircleCI.
#
# Usage:
#
#   mongo-install VERSION

set -e

# User supplied args
VERSION=$1
if [[ -z $VERSION ]]; then echo "Missing arg1 VERSION" && exit 1; fi

echo "Attempting to setup Mongo version '$VERSION'..."

echo "Stopping and removing currently installed Mongodb..."
# the service running Mongo 3.x is `mongod` vs `mongodb` in 2.4
sudo service mongod stop
sudo apt-get purge mongodb-org*

# Map minor versions to exact versions
if [ "$VERSION" == "2.4" ]; then VERSION="2.4.14"; fi

# For backwards compatibility, we only need to support installing this version
if [ "$VERSION" == "2.4.14" ]; then
    echo "Attempting to download Mongo version 2.4.14 ..."
    sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
    echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/mongodb.list
    sudo apt-get update
    sudo apt-get install -y mongodb-10gen=$VERSION

    echo "Restarting new version of Mongodb..."
    sudo service mongodb restart
    mongo --version

    echo "Mongo 2.4.14 installed successfully"
else
    echo "Mongo version $VERSION not supported by installer script."
    exit 1
fi
