#!/bin/bash

# Publishes build and application objects to Catapult.
#
# Usage:
#
#   report-card [DOCKER_USER] [DOCKER_PASS] [DOCKER_EMAIL] [GITHUB_TOKEN]
#

set -e

if [ $# -ne 4 ]; then
    echo "Incorrect number of arguments given. Expected 4, received $#"
    echo "Usage: report-card [DOCKER_USER] [DOCKER_PASS] [DOCKER_EMAIL] [GITHUB_TOKEN]"
    exit 1
fi

# User supplied args
DOCKER_USER=$1
DOCKER_PASS=$2
DOCKER_EMAIL=$3
GITHUB_TOKEN=$4

echo "Logging into DockerHub..."
docker login -u $DOCKER_USER -p $DOCKER_PASS --email="$DOCKER_EMAIL"

echo "Running report-card..."
docker run -t \
    -v `pwd`:/repo/$(basename `pwd`) \
    -e GITHUB_API_TOKEN=$GITHUB_TOKEN \
    clever/report-card --repo /repo/$(basename `pwd`) --publish
