#!/bin/bash

# Common functions used by more than on ci-script
#
# Usage:
#
#   . ./utils

set -e

install_awscli(){
  if type aws > /dev/null; then
    echo "AWS cli already installed"
    return
  fi

  echo "Installing AWS cli..."
  curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "/tmp/awscliv2.zip"
  unzip -q /tmp/awscliv2.zip -d /tmp
  sudo /tmp/aws/install
  echo "Completed AWS cli install"
}

install_yq(){
  if type yq > /dev/null; then
    echo "yq already installed"
    return
  fi

  echo "Installing yq..."
  wget https://github.com/mikefarah/yq/releases/download/v4.24.5/yq_linux_amd64 -O /tmp/yq
  sudo mv /tmp/yq /usr/local/bin/yq
  sudo chmod +x /usr/local/bin/yq
  echo "Compelted yq cli install"
}