#!/bin/bash

# Publishes workflows to Workflow Manager, via circle-ci-integrations.
#
# Usage:
#
#   workflow-publish [WF_URL] [WF_USER] [WF_PASS] [WF_JSON]
#
# Required circleci provided environment variables:
#
#  CIRCLE_PROJECT_REPONAME
#  CIRCLE_PROJECT_USERNAME
#  CIRCLE_BUILD_NUM
#

set -e

if [ $# -ne 4 ]; then
    echo "Incorrect number of arguments given. Expected 4, received $#"
    echo "Usage: workflow-publish [WF_URL] [WF_USER] [WF_PASS] [WF_FILE]"
    exit 1
fi


# User supplied args
export WF_URL=$1
if [[ -z $WF_URL ]]; then echo "Missing arg1 WF_URL" && exit 1; fi
export WF_USER=$2
if [[ -z $WF_USER ]]; then echo "Missing arg2 WF_USER" && exit 1; fi
export WF_PASS=$3
if [[ -z $WF_PASS ]]; then echo "Missing arg3 WF_PASS" && exit 1; fi
export WF_FILE=$4
if [[ -z $WF_FILE ]]; then echo "Missing arg4 WF_FILE" && exit 1; fi

# Set automatically by CircleCI
: ${CIRCLE_PROJECT_REPONAME?"Missing required env var"}
export REPO=$CIRCLE_PROJECT_REPONAME
: ${CIRCLE_PROJECT_USERNAME?"Missing required env var"}
export USER=$CIRCLE_PROJECT_USERNAME
: ${CIRCLE_BUILD_NUM?"Missing required env var"}
export BUILD_NUM=$CIRCLE_BUILD_NUM

CURL_DATA=$(python -c 'import json, os; print(json.dumps({
  "username": os.getenv("USER"),
  "reponame": os.getenv("REPO"),
  "buildnum": int(os.getenv("BUILD_NUM")),
  "workflow": open(os.getenv("WF_FILE"), "r").read(),
}))')
echo $CURL_DATA | python -m json.tool

CURL_OUTPUT="workflow-manager.out"
SC=$(curl -u $WF_USER:$WF_PASS \
  -w "%{http_code}" \
  --output $CURL_OUTPUT \
  -H "Content-Type: application/json" \
  -X POST \
  -d "$CURL_DATA" \
  $WF_URL)

if [ "$SC" -eq 200 ]; then
  echo "Successfully published workflow"
  rm -f $CURL_OUTPUT
  exit 0
else
  echo "Failed to publish workflow"
  echo "------------------------------------------------"
  cat $CURL_OUTPUT
  echo ""
  echo "------------------------------------------------"
  rm -f $CURL_OUTPUT
  exit 1
fi
