#!/bin/bash

# Logs into Docker registry, then builds and pushes docker image.
# Docker image is tagged with 7 character git commit SHA.
#
# Usage:
#
#   circleci-docker [DOCKERHUB_USER] [DOCKERHUB_PASS] [DOCKERHUB_EMAIL] [ORG]


set -e

# User supplied args
DOCKERHUB_USER=$1
if [[ -z $DOCKERHUB_USER ]]; then echo "Missing arg1 DOCKERHUB_USER" && exit 1; fi
DOCKERHUB_PASS=$2
if [[ -z $DOCKERHUB_PASS ]]; then echo "Missing arg2 DOCKERHUB_PASS" && exit 1; fi
DOCKERHUB_EMAIL=$3
if [[ -z $DOCKERHUB_EMAIL ]]; then echo "Missing arg3 DOCKERHUB_EMAIL" && exit 1; fi
ORG=$4
if [[ -z $ORG ]]; then echo "Missing arg4 ORG" && exit 1; fi

# Set automatically by CircleCI
: ${CIRCLE_PROJECT_REPONAME?"Missing required env var"}
REPO=$CIRCLE_PROJECT_REPONAME
: ${CIRCLE_SHA1?"Missing required env var"}
SHORT_SHA=${CIRCLE_SHA1:0:7}

echo "Logging into DockerHub..."
docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASS --email="$DOCKERHUB_EMAIL"

echo "Building docker image..."
docker build -t $ORG/$REPO:$SHORT_SHA .

echo "Pushing docker image..."
docker push $ORG/$REPO:$SHORT_SHA
