version: 2.1
jobs:
  build:
    working_directory: ~/Clever/ci-scripts
    docker:
    - image: cimg/go:1.22
    environment:
      GOPRIVATE: github.com/Clever/*
    steps:
    - checkout
    - run: make release
    - run: ./circleci/github-release $GH_RELEASE_TOKEN artifacts/
    # - run: if [ "${CIRCLE_BRANCH}" == "master" ]; then ./circleci/github-release $GH_RELEASE_TOKEN artifacts; fi;
