version: 2
jobs:
  build:
    working_directory: ~/Clever/ci-scripts
    docker:
    - image: circleci/buildpack-deps:18.04
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    steps:
    - run:
        command: cd $HOME && git clone --depth 1 -v https://github.com/Clever/ci-scripts.git && cd ci-scripts && git show --oneline -s
        name: Clone ci-scripts
    - checkout
    - run:
        command: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
        name: Set up CircleCI artifacts directories
    - run: mkdir artifacts
    - run: echo "foo" > artifacts/foo.txt
    - run:
        name: update version
        command: |-
          echo $CIRCLE_SHA1
          echo "${CIRCLE_SHA1:0:7}" > VERSION
    - run: ./circleci/github-release $GH_RELEASE_TOKEN artifacts/
