apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: go-lib-test
  description: test
  owner: eng-infra
spec:
  type: library
  lifecycle: development
  owner: team-name
  system: eng-infra
