// Package deploycreated provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/Clever/slingshot version v1.7.1-0.20260528184044-b35458a1f220 DO NOT EDIT.
package deploycreated

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
)

// AutoScalingConfig defines model for AutoScalingConfig.
type AutoScalingConfig struct {
	Max *int `json:"max,omitempty"`
	Min *int `json:"min,omitempty"`
}

// DeployOverrides defines model for DeployOverrides.
type DeployOverrides struct {
	Autoscaling *AutoScalingConfig `json:"autoscaling,omitempty"`
	Env         *[]EnvVarOverride  `json:"env,omitempty"`
}

// Detail defines model for Detail.
type Detail struct {
	App                string           `json:"app"`
	ClusterEnvironment string           `json:"clusterEnvironment"`
	Environment        string           `json:"environment"`
	Overrides          *DeployOverrides `json:"overrides,omitempty"`
	Repo               string           `json:"repo"`
	TargetRevision     string           `json:"targetRevision"`
	User               User             `json:"user"`
}

// EnvVarOverride defines model for EnvVarOverride.
type EnvVarOverride struct {
	Name  string `json:"name"`
	Value string `json:"value"`
}

// Event defines model for Event.
type Event struct {
	Account    *string    `json:"account,omitempty"`
	Detail     Detail     `json:"detail"`
	DetailType string     `json:"detail-type"`
	Id         *string    `json:"id,omitempty"`
	Region     *string    `json:"region,omitempty"`
	Resources  *[]string  `json:"resources,omitempty"`
	Source     string     `json:"source"`
	Time       *time.Time `json:"time,omitempty"`
	Version    *string    `json:"version,omitempty"`
}

// User defines model for User.
type User struct {
	Email          *string `json:"email,omitempty"`
	GithubUsername *string `json:"githubUsername,omitempty"`
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"hFNNb9swDP0v3I5u0mE334at5wEbusuwgyozDgfrYxRlLCj83wvJjpvYcnJKTD2Sj++Rr6Cd8c6ilQD1",
	"KwR9RKPy3y9R3E+tOrLtV2cP1KagZ+eRhTBDjPqffuTkEWogK9giw1CBIVt6GKpzyL38RS0J+g19507f",
	"e2SmZix73URFcWHkkT4/Mh6ghg/7d+L7ifV+TXmoAG2f8kjQhHsFnmz/S/GZDLzzVczqtDWAKOoKvL2/",
	"0CAIpwGGCnQXgyA/2Z7YWYNWijC88+4uFbs101LgoQJG74pFRXGL8gN7CuRsERID8r2Wz2Fym/FfJMYG",
	"6t9Zj6n1VOV6yFX3olR/Cg4sXFs5YZXB4iy96mLpZcE855/RRQL95NJiA7R2ccO+Zt6a295l1Ix/GOsU",
	"6lFTDDO2W0YyBhdZj1Tn61ivxNUBVDAmlaE06nxwbJRADY0SfMjRqiA+8saSLeS/HH3uPytY8uN52tFr",
	"O9BMiq+otCTH+JKyNlZlffcpRPYwnhFJl96afGk7zagEG7gYET7tHneP+Ww9WuUJavicQxV4JcfEbxje",
	"AgAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
