// Code generated by github.com/Clever/slingshot. DO NOT EDIT.

package deploycreated

import (
	"encoding/json"
	"fmt"
)

// ValidateAutoScalingConfig unmarshals data as JSON and validates it against the AutoScalingConfig
// schema component embedded in this package.
func ValidateAutoScalingConfig(data []byte) error {
	swagger, err := GetSwagger()
	if err != nil {
		return fmt.Errorf("load embedded spec: %w", err)
	}
	ref, ok := swagger.Components.Schemas["AutoScalingConfig"]
	if !ok || ref.Value == nil {
		return fmt.Errorf("schema AutoScalingConfig not found in embedded spec")
	}
	var v any
	if err := json.Unmarshal(data, &v); err != nil {
		return fmt.Errorf("unmarshal AutoScalingConfig: %w", err)
	}
	return ref.Value.VisitJSON(v)
}

// ValidateDeployOverrides unmarshals data as JSON and validates it against the DeployOverrides
// schema component embedded in this package.
func ValidateDeployOverrides(data []byte) error {
	swagger, err := GetSwagger()
	if err != nil {
		return fmt.Errorf("load embedded spec: %w", err)
	}
	ref, ok := swagger.Components.Schemas["DeployOverrides"]
	if !ok || ref.Value == nil {
		return fmt.Errorf("schema DeployOverrides not found in embedded spec")
	}
	var v any
	if err := json.Unmarshal(data, &v); err != nil {
		return fmt.Errorf("unmarshal DeployOverrides: %w", err)
	}
	return ref.Value.VisitJSON(v)
}

// ValidateDetail unmarshals data as JSON and validates it against the Detail
// schema component embedded in this package.
func ValidateDetail(data []byte) error {
	swagger, err := GetSwagger()
	if err != nil {
		return fmt.Errorf("load embedded spec: %w", err)
	}
	ref, ok := swagger.Components.Schemas["Detail"]
	if !ok || ref.Value == nil {
		return fmt.Errorf("schema Detail not found in embedded spec")
	}
	var v any
	if err := json.Unmarshal(data, &v); err != nil {
		return fmt.Errorf("unmarshal Detail: %w", err)
	}
	return ref.Value.VisitJSON(v)
}

// ValidateEnvVarOverride unmarshals data as JSON and validates it against the EnvVarOverride
// schema component embedded in this package.
func ValidateEnvVarOverride(data []byte) error {
	swagger, err := GetSwagger()
	if err != nil {
		return fmt.Errorf("load embedded spec: %w", err)
	}
	ref, ok := swagger.Components.Schemas["EnvVarOverride"]
	if !ok || ref.Value == nil {
		return fmt.Errorf("schema EnvVarOverride not found in embedded spec")
	}
	var v any
	if err := json.Unmarshal(data, &v); err != nil {
		return fmt.Errorf("unmarshal EnvVarOverride: %w", err)
	}
	return ref.Value.VisitJSON(v)
}

// ValidateEvent unmarshals data as JSON and validates it against the Event
// schema component embedded in this package.
func ValidateEvent(data []byte) error {
	swagger, err := GetSwagger()
	if err != nil {
		return fmt.Errorf("load embedded spec: %w", err)
	}
	ref, ok := swagger.Components.Schemas["Event"]
	if !ok || ref.Value == nil {
		return fmt.Errorf("schema Event not found in embedded spec")
	}
	var v any
	if err := json.Unmarshal(data, &v); err != nil {
		return fmt.Errorf("unmarshal Event: %w", err)
	}
	return ref.Value.VisitJSON(v)
}

// ValidateUser unmarshals data as JSON and validates it against the User
// schema component embedded in this package.
func ValidateUser(data []byte) error {
	swagger, err := GetSwagger()
	if err != nil {
		return fmt.Errorf("load embedded spec: %w", err)
	}
	ref, ok := swagger.Components.Schemas["User"]
	if !ok || ref.Value == nil {
		return fmt.Errorf("schema User not found in embedded spec")
	}
	var v any
	if err := json.Unmarshal(data, &v); err != nil {
		return fmt.Errorf("unmarshal User: %w", err)
	}
	return ref.Value.VisitJSON(v)
}
