name: Reusable LaunchDarkly Code References

on:
  workflow_call:
    secrets:
      LD_ACCESS_TOKEN:
        required: true
      GH_TOKEN:
        required: true
    inputs:
      project-key:
        required: false
        type: string
        default: 'default'
      environment-key:
        required: false
        type: string
        default: 'production'

jobs:
  find-ff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Find flags
        uses: launchdarkly/find-code-references-in-pull-request@v2
        id: find-flags
        with:
          project-key: ${{ inputs.project-key }}
          environment-key: ${{ inputs.environment-key }}
          access-token: ${{ secrets.LD_ACCESS_TOKEN }}
          repo-token: ${{ secrets.GH_TOKEN }}