# Basic workflow that approves and enables auto merge for PRs.
# Currently it is used to automate merging dependabot PRs or overridining the required review on a PR
# https://app.getguru.com/card/cbjEdoAi/Dependabot-and-auto-merging

name: Enable auto merge and then approve

on: workflow_call

jobs:
  auto-approve-merge-dependency-updates:
    name: Approve and Enable auto merge on dependabot PRs
    runs-on: ubuntu-latest
    steps:
    # Use github cli to enable auto approve. Only works on repos which have auto merge enabled and branch protections setup which is currently blocking a merge
    # for example still requires 1 review or a required ci step has not succeeded.
    - if: github.actor == 'dependabot[bot]'
      name: Enable Automerge
      run: gh pr merge --auto --merge "$PR_URL"
      env:
        PR_URL: ${{ github.event.pull_request.html_url }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    # v2.1.0 as of 02/23/2022, reviewed by eng-security.
    - if: github.actor == 'dependabot[bot]' || contains( github.event.pull_request.labels.*.name, 'auto approve')
      name: Approve
      uses: hmarr/auto-approve-action@v3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
